##############################################################
##         Initial Encounter Configuration                  ##
## Script Generated for Undergrad class of microelectronics ##
## Generated by Matheus Moreira/Fernando Moraes - 2018      ##
##                                                          ##
## Functionalities of this script:                          ##
##  -Place standard cells                                   ##
##  -Place core pins                                        ##
##  -Perform initial route of the design                    ##
##############################################################
##Place the design
place_design

##Place pins in the chip sides

edit_pin -side Top -layer 4 -spread_type center -spacing 3 -pin {clock reset {boot_address[31]} {boot_address[30]} {boot_address[29]} {boot_address[28]} {boot_address[27]} {boot_address[26]} {boot_address[25]} {boot_address[24]} {boot_address[23]} {boot_address[22]} {boot_address[21]} {boot_address[20]} {boot_address[19]} {boot_address[18]} {boot_address[17]} {boot_address[16]} {boot_address[15]} {boot_address[14]} {boot_address[13]} {boot_address[12]} {boot_address[11]} {boot_address[10]} {boot_address[9]} {boot_address[8]} {boot_address[7]} {boot_address[6]} {boot_address[5]} {boot_address[4]} {boot_address[3]} {boot_address[2]} {boot_address[1]} } {boot_address[0] }

edit_pin -side Left -layer 3 -spread_type center -spacing 3 -pin {{Bus2IP_Data[0]} {Bus2IP_Data[1]} {Bus2IP_Data[2]} {Bus2IP_Data[3]} {Bus2IP_Data[4]} {Bus2IP_Data[5]} {Bus2IP_Data[6]} {Bus2IP_Data[7]} Bus2IP_Reset}

edit_pin -side Bottom -layer 4 -spread_type center -spacing 3 -pin {{Bus2IP_WrCE[0]} {Bus2IP_WrCE[1]} {Bus2IP_WrCE[2]} {Bus2IP_WrCE[3]} {Bus2IP_WrCE[4]} {Bus2IP_WrCE[5]} {Bus2IP_WrCE[6]} {Bus2IP_WrCE[7]} {Bus2IP_WrCE[8]} {Bus2IP_WrCE[9]} {Bus2IP_WrCE[10]} {Bus2IP_WrCE[11]} {Bus2IP_WrCE[12]} {Bus2IP_WrCE[13]} {Bus2IP_WrCE[14]}}

edit_pin -side Right -layer 3 -spread_type center -spacing 3 -pin {{IP2Bus_Data[0]} {IP2Bus_Data[1]} {IP2Bus_Data[2]} {IP2Bus_Data[3]} {IP2Bus_Data[4]} {IP2Bus_Data[5]} {IP2Bus_Data[6]} {IP2Bus_Data[7]} user_int}

ccopt_design 

report_timing
