##############################################################
##         Initial Encounter Configuration                  ##
## Script Generated for Undergrad class of microelectronics ##
## Generated by Matheus Moreira/Fernando Moraes - 2018      ##
## GAPH/FACIN/PUCRS                                         ##
##                                                          ##
## Functionalities of this script:                          ##
##  -Route the design with nanoroute                        ##
##############################################################
route_design -global
route_detail
route_global_detail

# Optimization Post Route
eval_legacy {setAnalysisMode -analysisType onChipVariation}
opt_design -post_route

report_timing
